### ISSUE TITLE
kill directory after assets are collected in a tar file

### ISSUE THREAD

**Issue by brianredbeard** [coreos/mayday#19]
After mayday runs it leaves a directory behind in `/tmp`, i.e.:

```
$ find /tmp -maxdepth 1   -name "mayday*"
/tmp/mayday201504162157-956911310.tar.gz
/tmp/mayday201504162157-956911310
```

Ideally since all of the assets are captured in the tar file we should clean up the directory.

**Comment by tschuy** [comment]
Mayday no longer produces directories as a part of tar creation.
