### ISSUE TITLE
Sort keys within Docker configuration with  `--danger` operation

### ISSUE THREAD

**Issue by brianredbeard** [coreos/mayday#38]
There is a (accidental?) key sorting which occurs when pulling in the docker configuration when *not* running in `--danger` mode.  This has the side effect of making it easier to identify information in the json output.

It would be desirable to sort these keys in danger mode as well to make it easier to read the output.

**Comment by brianredbeard** [comment]
Affects https://github.com/coreos/mayday/pull/32

**Comment by tschuy** [comment]
Ok, that's easy.

The reason I wasn't doing this before is because I was able to keep from making a copy of the file  in memory, which felt reasonable. But I think the benefits of pretty print outweigh the cost of keeping a file in memory.

**Comment by tschuy** [comment]
Fixed in #32.
