### ISSUE TITLE
Insert placeholder in place of removed environment variables

### ISSUE THREAD

**Issue by brianredbeard** [coreos/mayday#39]
When removing the environment variables from Dockerfiles ([docker.go#L61](https://github.com/tschuy/mayday/blob/docker/mayday/docker/docker.go#L61)), it isn't clear that there were ever environment variables there to begin with.  It would be good to potentially inject a single variable to be used as a comment (the JSON format doesn't allow comments) informing the user that the variables were removed.

Alternately, replacing the _values_ with something to the effect of `scrubbed by mayday` would allow the user to see that the container was instantiated with the correct variable _names_ even if they don't know the values.

Affects #32

**Comment by tschuy** [comment]
I've pushed something to this effect in #32.
