### ISSUE TITLE
Save iptables rules

### ISSUE THREAD

**Issue by cgag** [coreos/mayday#50]
iptables-save dumps the rules to stdout, i think there are prettier commands that could be run as well, I don't actually know iptables very well. I think @bison might.

We might already do this I just wanted to write the idea down before I forget.

**Comment by bison** [comment]
Yeah, `iptables-save` dumps the raw rules. You can pipe that to `iptables-xml` to get XML. You can also just run something like `iptables -vnL` to list the rules with packet counts and things. That will only show the filter table by default.

**Comment by tschuy** [comment]
I'll just have it run `iptables -vnL` for now. If support or someone else using it wants a more specific format, we can easily change it.

Hopefully I don't decide this is the most important information for me to want to parse later on...

**Comment by brianredbeard** [comment]
Resolved as per #52
